config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :restaurants, only:[:index ,:show] do 
    resources :comments, only:[:create,:destroy]
    
    collection do
      get :feeds # 瀏覽所有餐廳的最新動態
      get :ranking # 瀏覽餐廳排名
    end

    
    member do
      get :dashboard # 瀏覽個別餐廳的 Dashboard
      post :favorite
      post :unfavorite
      post :like
      post :unlike
    end
  end
  root "restaurants#index"
  resources :users, only:[:index,:show,:edit,:update]
  resources :categories, only: :show
  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end



  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy,:update] 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments ,dependent: :restrict_with_error
  has_many :restaurants, through: :comments

  has_many :favorites, dependent: :destroy
  has_many :likes, dependent: :destroy
  
  has_many :favorited_restaurants, through: :favorites, source: :restaurant
  has_many :liked_restaurants, through: :likes, source: :restaurant
  
  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships
  has_many :inverse_followships ,class_name: "Followship", foreign_key: "following_id"
  has_many :followers, through: :inverse_followships, source: :user

  has_many :friendships, ->{where status: 3}, dependent: :destroy 
  has_many :friends, through: :friendships
  
  has_many :friend_invites, ->{where status: 2},class_name: "Friendship", dependent: :destroy 
  has_many :invites, through: :friend_invites, source: :friend

  has_many :friend_requests, ->{where status: 1},class_name: "Friendship",dependent: :destroy
  has_many :requests, through: :friend_requests, source: :friend
  mount_uploader :avatar, AvatarUploader
  def admin?
    self.role == "admin"
  end

  def is_following?(user)
    self.followings.include?(user)
  end
  #藉由status來判斷 1.已提出友好邀請 2.可同意好友邀請 3.已成為好友
  def is_friend?(user)
    if self.requests.include?(user)
      return 1
    elsif self.invites.include?(user) 
      return 2
    elsif self.friends.include?(user)
      return 3
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show,:edit,:update]
  
  def index
    @users = User.all
  end

  def show

    @commented_restaurants = @user.restaurants.uniq
    @favorited_restaurants = @user.favorited_restaurants
    @user_followings = @user.followings
    @user_followers = @user.followers
    @user_friends = @user.friends
    @friend_invites = @user.invites
  end

  def edit
    
    if @user != current_user
      redirect_to user_path(@user)
    end
    
  end

  def update
   
    if @user.update(user_params)
      redirect_to user_path(@user)
      flash[:notice] = "profile was successfully updated"
    else
      render :edit
      flash[:alert] = "profile was failed to update"
    end
  end



  private
  def user_params
    params.require(:user).permit(:avatar, :intro, :avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    <h2>Edit Profile</h2>

    <%= form_for @user do |f| %>
      <div class="form-group">
        <%= f.label :name,"Name" %>
        <%= f.text_field :name ,class: "form-control"%>
      </div>
      <div class="form-group">
        <%= f.label :intro,"Introduction" %>
        <%= f.text_field :intro ,class: "form-control"%>
      </div>
      <%= f.label :avatar, "Avatar" %>
      <%= image_tag @user.avatar, width: '300px' if @user.avatar? %>
      <%= f.file_field :avatar ,class: "form-control"%>
      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
      </div>    
    <% end %>
    </div>
    
  </div>
</div>

app/views/users/index.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" ><%= link_to "首頁",root_path%></li>
  <li role="presentation" ><%= link_to "最新動態",feeds_restaurants_path%></li>
  <li role="presentation" ><%= link_to "人氣餐廳（TOP10）",feeds_restaurants_path%></li>
  <li role="presentation" class="active"><a href="#">美食達人</a></li>
</ul>
<br>
<div class="container">
  <div class="row">    
    <% @users.each do |user|%>
      <div class="col-md-3 text-center user-item">
        <%= link_to user_path(user) do%>
          <%if !user.avatar?%>
            <%= image_tag "https://www.adjust.com/new-assets/images/site-images/interface/user.svg", class:"img-responsive center-block img-rounded" %>
          <% else%>
           <%= image_tag user.avatar, class:"img-responsive center-block img-rounded" %>
          <% end %>
          <h4><%= user.name%></h4>
        <% end %>
        <%= render partial: "shared/friend",locals:{user: user} %>

        <%= render partial: "shared/follow",locals:{user: user} %>

          
        
      </div>
    <% end %>   
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    

    <div class="col-md-4">
      <%if !@user.avatar?%>
        <%= image_tag "https://www.adjust.com/new-assets/images/site-images/interface/user.svg", class:"img-responsive center-block img-rounded" %>
      <% else%>
       <%= image_tag @user.avatar, class:"img-responsive center-block img-rounded" %>
      <% end %>
      
    </div>

    <div class="col-md-8">
      <h1><%= @user.name %></h1>
      <p><%= @user.email%></p>
      <%= simple_format @user.intro %>
      <% if @user.email == current_user.email %>
        <%= link_to 'Edit Profile', edit_user_path(@user), class: "btn btn-primary" %>
      <% else %>
         <%= render partial: "shared/friend",locals:{user: @user} %>
      <% end %>
    </div>


    <div class="clearfix"></div>
  </div>
  <br>

  <br>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user_followings.count%> 追蹤名單</h3>
      </div>
      <ul class="list-group">
      <% @user_followings.each do |user| %>
        <li class="list-group-item">
          <%= link_to user_path(user) do%>       
              <%if !user.avatar?%>
                <%= image_tag "https://www.adjust.com/new-assets/images/site-images/interface/user.svg",height: 30,width: 30 ,class:"img-circle" %>
              <% else%>
                <%= image_tag user.avatar, class:"img-circle " %>
              <% end %>         
              <%= link_to user.name ,user_path(user) %>
          <% end %>      
        </li>
      <% end %>
      </ul>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user_followers.count%> 粉絲</h3>
      </div>
      <ul class="list-group">
      <% @user_followers.each do |user| %>
        <li class="list-group-item">
          <%= link_to user_path(user) do%>         
              <%if !user.avatar?%>
                <%= image_tag "https://www.adjust.com/new-assets/images/site-images/interface/user.svg",height: 30,width: 30 ,class:"img-circle" %>
              <% else%>
                <%= image_tag user.avatar, height: 30,width: 30 ,class:"img-circle" %>
              <% end %>           
              <%= link_to user.name ,user_path(user) %>
          <% end %>      
        </li>
      <% end %>
      </ul>
    </div>
    
    <% if @user.email == current_user.email %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">
            
            <%= @user_friends.count%> 好友
          </h3>
        </div>
        <ul class="list-group">
        <% @user_friends.each do |user| %>
          <li class="list-group-item">
            <%= link_to user_path(user) do%>         
                <%if !user.avatar?%>
                  <%= image_tag "https://www.adjust.com/new-assets/images/site-images/interface/user.svg",height: 30,width: 30 ,class:"img-circle" %>
                <% else%>
                  <%= image_tag user.avatar, height: 30,width: 30 ,class:"img-circle"%>
                <% end %>           
                <%= link_to user.name ,user_path(user) %>
            <% end %>      
          </li>
        <% end %>
        </ul>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">
            <%= @friend_invites.count%> 好友邀請</h3>
        </div>
        <ul class="list-group">
        <% @friend_invites.each do |user| %>
          <li class="list-group-item">
            <%= link_to user_path(user) do%>         
                <%if !user.avatar?%>
                  <%= image_tag "https://www.adjust.com/new-assets/images/site-images/interface/user.svg",height: 30,width: 30 ,class:"img-circle" %>
                <% else%>
                  <%= image_tag user.avatar, height: 30,width: 30 ,class:"img-circle" %>
                <% end %>           
                <%= link_to user.name ,user_path(user) %>
                <%= link_to '同意好友邀請', friendship_path(user),method: :put ,class: "btn btn-warning"%>
            <% end %>      
          </li>
        <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @commented_restaurants.count%> 已評論餐廳</h3>
      </div>
      <div class="panel-body">
        <% @commented_restaurants.each do |restaurant| %>
          <div class="my-restaurant col-md-3">
            <%= link_to restaurant_path(restaurant) do%>
              <%if !restaurant.image?%>
                <%= image_tag "https://www.theriverside.co.uk/images/Inside-Restaurant.jpg", class:"img-responsive img-rounded" %>
              <% else%>
                <%= image_tag restaurant.image, class:"img-responsive img-rounded" %>
              <% end %>
            <% end %>
            <div class="caption">
              <h3><%= link_to restaurant.name ,restaurant_path(restaurant) %></h3>       
            </div>
          </div>
        <% end %>   
      </div>  
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @favorited_restaurants.count%> 收藏餐廳</h3>
      </div>
      <div class="panel-body">
        <% @favorited_restaurants.each do |restaurant| %>       
          <div class="my-restaurant col-md-3">
            <%= link_to restaurant_path(restaurant) do%>
              <%if !restaurant.image?%>
                <%= image_tag "https://www.theriverside.co.uk/images/Inside-Restaurant.jpg", class:"img-responsive img-rounded" %>
              <% else%>
                <%= image_tag restaurant.image, class:"img-responsive img-rounded" %>
              <% end %>
            <% end %>  
            <div class="caption">
              <h3><%= link_to restaurant.name ,restaurant_path(restaurant) %></h3>
            </div>
          </div>  
        <% end %>
      </div>
    </div>
  </div>

</div>