config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :restaurants, only:[:index ,:show] do 
    resources :comments, only:[:create,:destroy]
    
    collection do
      get :feeds # 瀏覽所有餐廳的最新動態
      get :ranking # 瀏覽餐廳排名
    end

    
    member do
      get :dashboard # 瀏覽個別餐廳的 Dashboard
      post :favorite
      post :unfavorite
      post :like
      post :unlike
    end
  end
  root "restaurants#index"
  resources :users, only:[:index,:show,:edit,:update]
  resources :categories, only: :show
  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end



  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy,:update] 

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  mount_uploader  :image, PhotoUploader
  validates_presence_of :name
  belongs_to :category, optional: true
  has_many :comments ,dependent: :destroy
  has_many :favorites , dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :liked_users, through: :likes, source: :user
  def is_favorited?(user)
    self.favorited_users.include?(user)
  end
  def is_liked?(user)
    self.liked_users.include?(user)
  end


end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController
  
  
  before_action :set_restaurant, only: [:show,  :edit,  :update,  :destroy]
  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
  end

  def new
    @restaurant = Restaurant.new

  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "restaurant was successfully created"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "restaurant was failed to created"
      render :new
    end
  end

  def show
    
  end

  def edit
    
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to admin_restaurant_path(@restaurant)
      flash[:notice] = "restaurant was successfully updated"
    else
      render :edit
      flash[:alert] = "restaurant was failed to update"
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to admin_restaurants_path
    flash[:alert] = "restaurant was delete"
  end

  private
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])  
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image,:category_id)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :dashboard, :favorite, :unfavorite, :like, :unlike]
  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all
  end

  def show
    
    @comment = Comment.new
    
  end

  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end

  def dashboard
    
  end

  def favorite
    @restaurant.favorites.create!(user: current_user)
    
    redirect_back(fallback_location: root_path)
  end

  def unfavorite
    favorite = Favorite.where(restaurant: @restaurant, user: current_user).first

    favorite.destroy
    redirect_back(fallback_location: root_path)
  end

  def like
    @restaurant.likes.create!(user: current_user)
    redirect_back(fallback_location: root_path)
  end

  def unlike
    like = Like.where(restaurant: @restaurant, user: current_user).first
    like.destroy
    redirect_back(fallback_location: root_path)
  end

  def ranking
    Restaurant.all.each do |restaurant|
      restaurant.favorites_count = restaurant.favorited_users.count
      restaurant.save
    end

    @favorites_restaurants = Restaurant.order(favorites_count: :desc).limit(10)
  end

  private
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])  
  end
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/dashboard.html.erb
<h1><%= @restaurant.name %>'s Dashboard</h1>
<hr>
<ul>
  <li>有 <%= @restaurant.comments.count %> 筆評論</li>
  <li>這家餐廳的平均價位為 $XXX</li>
  <li>有 XX 人收藏這家餐廳</li>
</ul>

app/views/restaurants/feeds.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" ><%= link_to "首頁",root_path%></li>
  <li role="presentation" class="active"><a href="#">最新動態</a></li>
  <li role="presentation" ><%= link_to "人氣餐廳（TOP10）",ranking_restaurants_path%></li>
  <li role="presentation" ><%= link_to "美食達人",users_path%></li>
</ul>
<br>

<div class="container">
  <h2>餐廳最新動態</h2>
  <br>
  <div class="col-sm-6 col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">最新餐廳</div>
      <div class="panel-body">
        <% @recent_restaurants.each do |restaurant| %>
        <h4><%= link_to restaurant.name , restaurant_path(restaurant) %></h4>
        <p><%= restaurant.category.name %></p>
        <p><%= restaurant.description %></p>
        <hr>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">最新評論</div>
      <div class="panel-body">
        <% @recent_comments.each do |comment| %>
        <h4><%= link_to comment.restaurant.name, restaurant_path(comment.restaurant) %></h4>
        <p><%= comment.content %></p>
        <p>by <%= link_to comment.user.name, user_path(comment.user) %></p>
        <hr>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="#">首頁</a></li>
  <li role="presentation" ><%= link_to "最新動態",feeds_restaurants_path%></li>
  <li role="presentation" ><%= link_to "人氣餐廳（TOP10）",ranking_restaurants_path%></li>
  <li role="presentation" ><%= link_to "美食達人",users_path%></li>
</ul>
<br>
<div class="container">
  <div class="row">
    <ul class="nav nav-pills">
      <li class="active" role="presentation"><%= link_to "全部餐廳", root_path %></li>
      <% @categories.each do |category| %>
      <li role="presentation"><%= link_to category.name, category_path(category) %></li>
      <% end %>
    </ul>
    <br>
  <!-- restaurant list -->
  <br>

  <%= render partial: "shared/restaurant_list"%>
  
  </div>

</div>

app/views/restaurants/ranking.html.erb
<ul class="nav nav-tabs">
  <li role="presentation" ><%= link_to "首頁",root_path%></li>
  <li role="presentation" ><%= link_to "最新動態",feeds_restaurants_path%></li>
  <li role="presentation" class="active"><a href="#">人氣餐廳（TOP10）</a></li>
  <li role="presentation" ><%= link_to "美食達人",users_path%></li>
</ul>
<br>

<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      
      <div class="page header">
        <h1>Top 10 人氣餐廳<small>(Favorites)</small></h1>
      </div>

      <% @favorites_restaurants.each do |restaurant|%>
        <div class="ranking-item">
          <div class="col-md-3">
            <%= link_to restaurant_path(restaurant) do%>
              <%if !restaurant.image?%>
                <%= image_tag "https://www.theriverside.co.uk/images/Inside-Restaurant.jpg", class:"img-responsive center-block" %>
              <% else%>
               <%= image_tag restaurant.image, class:"img-responsive center-block" %>
              <% end %>
            <% end %>
          </div>
          

          <div class="col-md-9">
            <h3>
              <%= link_to restaurant.name ,restaurant_path(restaurant) %>
              <span class="label label-default">收藏數：<%= restaurant.favorites_count %></span>    
            </h3>
            
            <p><%= truncate(restaurant.description, length: 200)%></p>
            <%= render partial: "shared/favorite", locals: {restaurant: restaurant}%>
            
          </div>
          <div class="clearfix"></div>
        </div>

      <% end %>
    </div>
  </div>
  
  
  
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1><%= @restaurant.name %></h1>
    </div>

    <div class="col-md-4 ">
      <div class="restaurant-item">
      <%if !@restaurant.image?%>
        <%= image_tag "https://www.theriverside.co.uk/images/Inside-Restaurant.jpg", class:"img-responsive center-block" %>
      <% else%>
       <%= image_tag @restaurant.image, class:"img-responsive center-block" %>
      <% end %>
      </div>
      <br>
      <div class="well">
        <ul class="list-unstyled">
          <li><strong>Opening Hours:<%= @restaurant.opening_hours %></li>  
          <li><strong>Tel: <%= @restaurant.tel %></li> 
          <li><strong>Address: <%= @restaurant.address %></li>
                 
        </ul>

      </div>
      

    </div>

    <div class="col-md-8">
      <%= simple_format @restaurant.description %>
      <hr>
      <%= link_to "Dashboard",dashboard_restaurant_path(@restaurant),class: "btn btn-primary"%>
      <%= render partial: "shared/favorite", locals: {restaurant: @restaurant}%>
      <%= render partial: "shared/like", locals: {restaurant: @restaurant}%>
      
    </div>

    <div class="clearfix"></div>
  </div>
  <div class="row">
   <%= form_for [@restaurant, @comment] do |f| %>
    <div class="form-group">
      <%= f.text_area :content, placeholder: "留個言吧", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
      <%= f.button "Cancel", type: :reset, class: "btn btn-default" %>
    </div>
  <% end %>
  <!-- 顯示與餐廳相關的評論 -->
    <% @restaurant.comments.each do |comment| %>
    <div>
      <% if comment.user.name == "" %>
        <h4><%= comment.user.email.split('@').first %></h4>
      <% else %>
        <h4><%= comment.user.name %></h4>
      <% end %>
      <p><%= simple_format comment.content %></p>
      <p class="text-muted">
        <em><%= time_ago_in_words(comment.created_at) %> </em>
        <% if current_user.admin? %>
        <%= link_to "Delete", restaurant_comment_path(@restaurant, comment), method: :delete %>
        <% end %>
      </p>
      
    </div>
    
    <hr>
    <% end %>
  </div>
</div>

<div>
  <hr>
</div>