config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :restaurants, only:[:index ,:show] do 
    resources :comments, only:[:create,:destroy]
    
    collection do
      get :feeds # 瀏覽所有餐廳的最新動態
      get :ranking # 瀏覽餐廳排名
    end

    
    member do
      get :dashboard # 瀏覽個別餐廳的 Dashboard
      post :favorite
      post :unfavorite
      post :like
      post :unlike
    end
  end
  root "restaurants#index"
  resources :users, only:[:index,:show,:edit,:update]
  resources :categories, only: :show
  namespace :admin do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end



  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy,:update] 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name

  has_many :restaurants, dependent: :restrict_with_error
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/followship.rb
class Followship < ApplicationRecord
  validates :following_id, uniqueness: {scope: :user_id }
  belongs_to :user
  belongs_to :following, class_name: "User"
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  mount_uploader  :image, PhotoUploader
  validates_presence_of :name
  belongs_to :category, optional: true
  has_many :comments ,dependent: :destroy
  has_many :favorites , dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :liked_users, through: :likes, source: :user
  def is_favorited?(user)
    self.favorited_users.include?(user)
  end
  def is_liked?(user)
    self.liked_users.include?(user)
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments ,dependent: :restrict_with_error
  has_many :restaurants, through: :comments

  has_many :favorites, dependent: :destroy
  has_many :likes, dependent: :destroy
  
  has_many :favorited_restaurants, through: :favorites, source: :restaurant
  has_many :liked_restaurants, through: :likes, source: :restaurant
  
  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships
  has_many :inverse_followships ,class_name: "Followship", foreign_key: "following_id"
  has_many :followers, through: :inverse_followships, source: :user

  has_many :friendships, ->{where status: 3}, dependent: :destroy 
  has_many :friends, through: :friendships
  
  has_many :friend_invites, ->{where status: 2},class_name: "Friendship", dependent: :destroy 
  has_many :invites, through: :friend_invites, source: :friend

  has_many :friend_requests, ->{where status: 1},class_name: "Friendship",dependent: :destroy
  has_many :requests, through: :friend_requests, source: :friend
  mount_uploader :avatar, AvatarUploader
  def admin?
    self.role == "admin"
  end

  def is_following?(user)
    self.followings.include?(user)
  end
  #藉由status來判斷 1.已提出友好邀請 2.可同意好友邀請 3.已成為好友
  def is_friend?(user)
    if self.requests.include?(user)
      return 1
    elsif self.invites.include?(user) 
      return 2
    elsif self.friends.include?(user)
      return 3
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters , if: :devise_controller?
  before_action :authenticate_user! 
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  @categories = Category.all
  @category = Category.find(params[:id])
  @restaurants = @category.restaurants.page(params[:page]).per(9)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_restaurant, only:[:create,:destroy]

  def create
    
    @comment = @restaurant.comments.build(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @comment = Comment.find(params[:id])

    if current_user.admin?
      @comment.destroy
      redirect_to restaurant_path(@restaurant)
    end
  end


  private
  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end


end
 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show,:edit,:update]
  
  def index
    @users = User.all
  end

  def show

    @commented_restaurants = @user.restaurants.uniq
    @favorited_restaurants = @user.favorited_restaurants
    @user_followings = @user.followings
    @user_followers = @user.followers
    @user_friends = @user.friends
    @friend_invites = @user.invites
  end

  def edit
    
    if @user != current_user
      redirect_to user_path(@user)
    end
    
  end

  def update
   
    if @user.update(user_params)
      redirect_to user_path(@user)
      flash[:notice] = "profile was successfully updated"
    else
      render :edit
      flash[:alert] = "profile was failed to update"
    end
  end



  private
  def user_params
    params.require(:user).permit(:avatar, :intro, :avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestuarantForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body >
    

  <!-- 導覽列 -->
  <nav  class="navbar navbar-default  navbar-inverse">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        
        <%= link_to '<i class = "glyphicon glyphicon-home" aria-hidden="true"></i> Home'.html_safe,root_path, class: "navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="pull-right nav navbar-nav ">
          <% if current_user%>
            <p class="navbar-text glyphicon glyphicon-user"> Hi, <%= current_user.email %></p>
            <% if current_user.admin? %>
              <li><%= link_to('Admin後台',admin_restaurants_path) %></li>
            <% end %>
            <li><%= link_to('Profile', user_path(current_user))  %></li>
            <li><%= link_to('<i class = "glyphicon glyphicon-log-out" aria-hidden="true"></i>Log out'.html_safe, destroy_user_session_path,:method => :delete)%></li> |
            <li><%= link_to('修改密碼', edit_user_registration_path)  %></li>
          <% else %>
            <li><%= link_to('註冊', new_user_registration_path) %></li>
            <li><%= link_to('登入', new_user_session_path) %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  
  <% if flash[:notice] %>
  <div class="container">
    <div class="row">
      <div class="alert alert-success alert-dismisssible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
    </div>
  </div>
  <% end %>
  
  <% if flash[:alert] %>
  <div class="container">
    <div class="row">
      <div class="alert alert-danger alert-dismisssible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= alert %>
      </div>
    </div>
  </div>
  <% end %>

  <%= yield %>
  
  </body>
</html>

app/views/shared/_favorite.html.erb
<%if !restaurant.is_favorited?(current_user)%>
  <%= link_to "Favorite",favorite_restaurant_path(restaurant),method: :post,class: "btn btn-primary"%>
<%else%>
  <%= link_to "Unfavorite",unfavorite_restaurant_path(restaurant),method: :post,class: "btn btn-primary"%> 
<%end%>

app/views/shared/_follow.html.erb
<% if user != current_user%>
  <% if current_user.is_following?(user) %>
    <%= link_to '取消追蹤', followship_path(user),method: :delete ,class: "btn btn-danger"%>
  <% else %>
    <%= link_to '追蹤', followships_path(following_id: user.id),method: :post,class: "btn btn-success" %>
  <% end %>
<% end %>

app/views/shared/_friend.html.erb
<% if user != current_user%>
  <% if current_user.is_friend?(user) ==3 %>
    <%= link_to '刪除好友', friendship_path(user),method: :delete ,class: "btn btn-danger"%>
  <% elsif current_user.is_friend?(user) ==2 %>
    <%= link_to '同意好友邀請', friendship_path(user),method: :put ,class: "btn btn-warning"%>
  <% elsif current_user.is_friend?(user) ==1 %>
    <%= link_to '取消好友邀請', friendship_path(user),method: :delete ,class: "btn btn-danger"%>
  <% else %>
    <%= link_to '提出好友邀請', friendships_path(friend_id: user.id),method: :post,class: "btn btn-success" %>
  <% end %>
<% end %>

app/views/shared/_like.html.erb
<% if !restaurant.is_liked?(current_user) %>
  <%= link_to "Like",like_restaurant_path(restaurant),method: :post,class: "btn btn-primary"%>
<% else %>
  <%= link_to "UnLike",unlike_restaurant_path(restaurant),method: :post,class: "btn btn-primary"%>
<% end %>

app/views/shared/_restaurant_list.html.erb
<!-- restaurant list -->
<% @restaurants.each do |restaurant|%>
  <div class="col-sm-6 col-md-4">
    <div class="restaurant-item">
      <%= link_to restaurant_path(restaurant) do%>
        <%if !restaurant.image?%>
          <%= image_tag "https://www.theriverside.co.uk/images/Inside-Restaurant.jpg", class:"img-responsive center-block" %>
        <% else%>
         <%= image_tag restaurant.image, class:"img-responsive center-block" %>
        <% end %>
      <% end %>

      <div class="caption">
        <h3><%= link_to restaurant.name ,restaurant_path(restaurant) %></h3>
        <p class="label label-default"><%= restaurant.category.name %></p>
        <p><%= truncate(restaurant.description, length: 80)%></p>
        <%= render partial: "shared/favorite", locals: {restaurant: restaurant}%>
        <%= render partial: "shared/like", locals: {restaurant: restaurant}%>
      </div>
      
    </div>
  </div>
<% end %>
<div class="text-center">
  <%= paginate @restaurants %>
</div>
</div>